import Foundation

struct AppConstants {
    static let tableViewdelegatesViewController = "TableViewDelegatesCell"
    static let tableViewDemoViewController = "TableViewCellWithXIB"
    static let cartTableViewController = "CartItemCell"
    static let jobProfileTableViewController = "ProfileDetailsCell"
    static let collectionViewDemoViewController = "GameCharactersCollectionViewCell"
    static let collectionViewDemoViewControllerHeader = "GameCharacterCollectionHeader"
    static let phPickerDemoViewController = "NatureImageCell"
    static let collectionViewDemoViewControllerHeaderHeight = Double(50)
    static let progressIncrementValue = 0.01
    static let progressFinishValue = 1.0
    static let mobileNoDigiLimit = 10
    static let gameCharactersCellMinLineSpacing = 30
    static let imageViewAnimationDuration = TimeInterval(3)
    static let imageViewAnimationRepeatCount = 10
    static let appleWebsite = "https://www.apple.com/in/"
    static let webWhatsAppUrl = "https://web.whatsapp.com/"
    static let amazonUrl = "https://www.amazon.in/"
    static let phPickerImageSelectionLimit = 3
    static let uiSearchBarCellForCountry = "cellForCountry"
    static let amazon = "amazon"
    static let alphaValueforImgView = CGFloat(0.8)
    static let minimumRegionMetersValue = 300
    static let fontSize = 14
    static let taskPickerViewNumberOfComponents = 2
    static let zeroIndexComponents = 0
    static let firstIndexComponents = 1
    static let reuseIdentifier = "reuse"
    static let oneComponentforPickerView = 1
    static let viewControllerListTableViewCell = "ViewControllerTableViewCell"
    static let parkingDetailTableViewCell = "ParkingDetailTableViewCell"
    static let amenitiesCollectionViewCell = "AmenitiesCollectionViewCell"
    static let userTableViewCell = "UserTableViewCell"
    static let collectionviewAmenitiesWidth = 2.1
    static let collectionviewAmenitiesHeight = 30.0
    static let parkingLotViewCell = "ParkingLotViewCell"
    static let timesheetViewCell = "TimesheetViewCell"
    static let zeroConstantValue = 0
    static let leadingAnchorConstantParkingLot = 20
    static let trailingAnchorConstantParkingLot = -50
    static let labelLeftleadingAnchorParkingLot = 10
    static let labelCenterCenterXAnchorParkingLot = -20
    static let labelRightTrailingAnchorParkingLot = -100
    static let circlePauseIcon = "pause.circle"
    static let circlePlayIcon = "play.circle"
    static let userProfileTableViewCell = "UserProfileTableViewCell"
    static let firstPage = 1
    static let secondPage = 2
    static let startupTableViewCell = "StartupTableViewCell"
    static let signUpViewController = "SignUpViewController"
    
    //String Constants
    static let shareWithWhatsapp = "Share With WhatsApp"
    static let openAmazon = "Open Amazon"
    static let contextMenuTitle = "Actions"
    static let ShowTitle = "Modal Presentation Style: Show"
    static let presentTitle = "Modal Presentation Style: Present"
    static let showDetailTitle = "Modal Presentation Style: Show Details"
    static let popoverTitle = "Modal Presentation Style: Popover"
    static let navigationControllerTitle = "Navigation"
    static let previousTitleForBackItem = "Previous"
    static let homeTitleForBarItem = "Home"
    static let backTitleForBarItem = "Back"
    static let greenColor = "Green"
    static let yellowColor = "Yellow"
    static let parkingLotName = "Parking Lot name"
    static let action = "Action"
    static let parkingName = "Parking Name"
    static let date = "Date"
    static let startTime = "Start Time"
    static let parkingNotAvailable = "Parking Lot Not Available"
    static let alertMessageAlreadyParkingAlloted = "You have already booked parking lot. After stop your current parking lot you can use another parking lot."
    static let ok = "OK"
    static let dataNotFound = "Data Not Found"
    static let dataNotFoundMessage = "Enter Detail Data is not available."
    static let dataNotDeleted = "Data Can't Remove"
    static let dataNotDeletedMessage = "Enter ID Data Can't Remove Due To Some Error."
    static let imageUploadErrorTitle = "Uploading Error"
    static let imageUploadErrorMessage = "Image Not upload successfully."
    static let accountRegistrationTitle = "Account Registration"
    static let accountLoginTitle = "Account Login"
    static let credentials = "Credentials:"
    static let errorCode = "Error Code:"
}
